version: "3"
services:
  app:
    container_name: nodeapp
    restart: always
    build: .
    command: npm start
    volumes:
      - ./:/usr/src/simpleapp
    links:
      - redis
    ports:
      - "8080:8080"
    depends_on:
      - redis

  mongodb:
    container_name: mongodb
    image: mongo:4.1.8-xenial
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
